import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Modal from "../components/Modal";
import Formulario from "../components/Formulario";
import { useRouter } from "next/router";
import useCarreras from "../hooks/useCarreras";

export default function Layout({ children, pagina }) {
  const { pathname } = useRouter();
  const { boton, setBoton } = useCarreras();

  return (
    <>
      <Head>
        <title>{`iestp la unión | ${pagina}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content="#007BFF" />
        <link rel="apple-touch-icon" href="/img/logo.ico" />
        <link rel="icon" href="/img/logo.ico" />
      </Head>
      <Header />
      <main>{children}</main>
      {pathname !== "/contacto" && (
        <>
          {boton && (
            <Modal setEstado={setBoton}>
              <div className="bg-white p-sm-5 p-4 rounded">
                <Formulario />
              </div>
            </Modal>
          )}
          <button
            className="btn-comunicate"
            onClick={() => setBoton(true)}
            title="Contactar"
          >
            <svg
              className="w-6 h-6"
              fill="none"
              width={30}
              height={30}
              stroke="currentColor"
              viewBox="0 0 24 24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z"
              />
            </svg>
          </button>
        </>
      )}
      <Footer />
    </>
  );
}
